# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "poc-service-passkey"
main = "src/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "poc_rbm_service_passkey-db"
database_id = "e7711979-1c74-4344-aced-14eb1b26ba56"
migrations_dir = "drizzle"

[vars]
BETTER_AUTH_SECRET = "NnrBeDsGainH90zQli+YvuPO8wAzUGxTUgfKE9XwQ9A="
BETTER_AUTH_URL="https://poc-service-passkey.yesid1995gonzalez.workers.dev"


# To protect the database id, we ignore this
# file when committing to the repo by running once:
# git update-index --assume-unchanged wrangler.toml
#
# Put back in git if you need to commit this file:
# git update-index --no-assume-unchanged wrangler.toml